Repository swiftwasm/carton, pull requests merged in 2020-10, with the labels that each got.

#116 Allow changing dev server's port
  Sources/carton/Commands/Dev.swift
  Sources/carton/Server/Application.swift
  Sources/carton/Server/HTML.swift
  Sources/carton/Server/Server.swift
  entrypoint/dev.js
Labels: enhancement

#117 Automatically open a browser window when Dev Server starts
  README.md
  Sources/carton/Commands/Dev.swift
  Sources/carton/Server/Server.swift
Labels: enhancement

#118 Update dependencies
  Package.resolved
Labels: dependencies

#124 Add @carson-katri and @kateinoigakukun to `FUNDING.yml`
  .github/FUNDING.yml
  README.md
Labels: documentation

#125 Update dependencies
  Package.resolved
Labels: dependencies

#122 Pretty print diagnostics
  Package.resolved
  Package.swift
  Package@swift-5.2.swift
  Sources/CartonHelpers/DiagnosticsParser.swift
  Sources/CartonHelpers/InteractiveWriter.swift
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/CartonHelpers/TerminalController.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Server/Server.swift
Labels: enhancement

#128 Bump default toolchain, make i64 bug reproducible
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  TestApp/.swift-version
  TestApp/Sources/TestApp/main.swift
Labels: bug, dependencies

#133 Update dependencies
  Package.resolved
Labels: dependencies

#130 Bump toolchain, use `--enable-test-discovery`
  Package.resolved
  Package.swift
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/SwiftToolchain/Toolchain.swift
  TestApp/Tests/LinuxMain.swift
  TestApp/Tests/Tests/XCTestManifests.swift
Labels: enhancement

#131 Add separate Builder class, use WasmTransformer
  .vscode/tasks.json
  Package.resolved
  Package.swift
  Package@swift-5.2.swift
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/SwiftToolchain/Builder.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Server/Server.swift
Labels: bug

#135 Remove sudo usage from `install_ubuntu_deps.sh`
  .github/workflows/swift.yml
  install_ubuntu_deps.sh
Labels: continuous integration, enhancement

#132 Build on macOS Big Sur with GitHub Actions
  .github/workflows/swift.yml
Labels: continuous integration

#134 Fix support for Ubuntu 20.04, use GHA for SwiftLint
  .github/workflows/danger.yml
  .github/workflows/swift.yml
  .github/workflows/swiftlint.yml
  Dangerfile.swift
  README.md
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
Labels: bug

#136 Add Dockerfile, mention the Docker image in `README.md`
  .dockerignore
  .github/workflows/swift.yml
  Dockerfile
  README.md
Labels: documentation, enhancement

#137 Add support for signed `.pkg` archives on macOS
  Dockerfile
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainInstallation.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
Labels: bug, enhancement

#138 Avoid repeated `loadingMessage` in `ProcessRunner`
  Sources/CartonHelpers/ProcessRunner.swift
Labels: bug

#139 Bump JavaScriptKit to 0.8, stop checking revision
  Sources/SwiftToolchain/Toolchain.swift
  package-lock.json
  package.json
Labels: dependencies

#140 Update JavaScriptKit version in TestApp
  TestApp/Package.resolved
  TestApp/Package.swift
  TestApp/Sources/TestApp/main.swift
Labels: dependencies

#143 Update dependencies
  Package.resolved
Labels: dependencies

#142 Fix error message output
  .github/workflows/swift.yml
  Package.swift
  Sources/CartonHelpers/DiagnosticsParser.swift
  Tests/CartonTests/CartonTests.swift
  Tests/CartonTests/XCTestManifests.swift
  Tests/LinuxMain.swift
Labels: bug

#145 Use Xcode 12.2 on macOS Big Sur
  .github/workflows/swift.yml
Labels: continuous integration, dependencies

#141 Stop using destination.json
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/SwiftToolchain/Destination.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton/Commands/Bundle.swift
  Sources/carton/Commands/Dev.swift
  TestApp/Sources/TestApp/main.swift
Labels: enhancement, refactor

#144 Pretty print `carton test` output
  Sources/CartonHelpers/Parsers/DiagnosticsParser.swift
  Sources/CartonHelpers/Parsers/ProcessOutputParser.swift
  Sources/CartonHelpers/Parsers/String+color.swift
  Sources/CartonHelpers/Parsers/String+regex.swift
  Sources/CartonHelpers/Parsers/TestsParser.swift
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/SwiftToolchain/Builder.swift
  Sources/carton/Commands/Test.swift
Labels: enhancement

#148 Fix handling of binaries with `.wasm` extension
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/SwiftToolchain/Toolchain.swift
Labels: bug

#147 Update toolchain and remove extra compiler flags
  .gitignore
  Sources/SwiftToolchain/Toolchain.swift
Labels: refactor
