Repository swiftwasm/carton, pull requests merged in 2020-11, with the labels that each got.

#150 Build only test product and its deps for testing
  .vscode/tasks.json
  Dockerfile
  Sources/SwiftToolchain/Toolchain.swift
Labels: bug

#152 Format testing time to two decimal places
  Sources/CartonHelpers/Parsers/TestsParser.swift
Labels: enhancement

#153 Fix handling of test products with .wasm extension
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/SwiftToolchain/Toolchain.swift
Labels: bug

#154 Use ghcr.io/swiftwasm/swift as base image
  Dockerfile
  Sources/CartonHelpers/DefaultToolchain.swift
Labels: dependencies, refactor

#156 Remove wabt dependency
  Brewfile
  Package.resolved
  Package.swift
  Sources/carton-release/Formula.swift
  Sources/carton/Commands/Bundle.swift
  install_ubuntu_deps.sh
Labels: enhancement, refactor

#157 Support system installed toolchain
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainInstallation.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/SwiftToolchain/ToolchainResolver.swift
  Sources/carton/Commands/SDK/Local.swift
  Sources/carton/Commands/SDK/Versions.swift
Labels: enhancement

#158 Bump version to 0.8.0, update `CHANGELOG.md`
  CHANGELOG.md
  Sources/CartonHelpers/Version.swift
  Tests/CartonTests/CartonTests.swift
  package-lock.json
  package.json
Labels: documentation

#161 Add image source label
  Dockerfile
Labels: refactor

#159 Update dependencies
  Package.resolved
Labels: dependencies

#160 Update Tokamak version used in init template
  Sources/carton/Model/Template.swift
Labels: refactor

#163 Bump version to 0.8.1, update `CHANGELOG.md`
  CHANGELOG.md
  Sources/CartonHelpers/Version.swift
  Tests/CartonTests/CartonTests.swift
  package-lock.json
  package.json
Labels: documentation

#164 Remove wasm-strip from log comment
  Sources/carton/Commands/Bundle.swift
Labels: refactor

#165 Add minimum deployment target in template
  Sources/carton/Model/Template.swift
Labels: refactor

#170 Update dependencies
  Package.resolved
Labels: dependencies

#172 Update dependencies
  Package.resolved
Labels: dependencies

#162 Demangle and print Firefox stack traces in terminal
  Sources/CartonHelpers/Parsers/FirefoxStackTrace.swift
  Sources/CartonHelpers/Parsers/String+Regex.swift
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/CartonHelpers/StackTrace.swift
  Sources/SwiftToolchain/Builder.swift
  Sources/SwiftToolchain/DestinationEnvironment.swift
  Sources/carton-release/HashArchive.swift
  Sources/carton/Commands/Bundle.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Commands/Test.swift
  Sources/carton/Model/Entrypoint.swift
  Sources/carton/Server/Application.swift
  Sources/carton/Server/Environment+UserAgent.swift
  Sources/carton/Server/Server.swift
  Sources/carton/Server/StaticArchive.swift
  Tests/CartonTests/CartonTests.swift
  Tests/CartonTests/StackTraceTests.swift
  entrypoint/bundle.js
  entrypoint/dev.js
Labels: enhancement

#178 Bump `defaultToolchainVersion` to 5.3.1
  Dockerfile
  Sources/CartonHelpers/DefaultToolchain.swift
Labels: dependencies

#179 Update dependencies
  Package.resolved
Labels: dependencies
