Repository swiftwasm/carton, pull requests merged in 2020-08, with the labels that each got.

#80 Update dependencies
  Package.resolved
Labels: dependencies

#82 Update dependencies
  Package.resolved
Labels: dependencies

#83 Update dependencies
  Package.resolved
Labels: dependencies

#84 Update dependencies
  Package.resolved
Labels: dependencies

#85 Close WebSocket connections after HTTP server exits
  .swiftformat
  .swiftlint.yml
  Sources/SwiftToolchain/FileDownloadDelegate.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton/Model/Template.swift
  Sources/carton/Server/Server.swift
Labels: bug

#87 Update default toolchain version
  README.md
  Sources/CartonHelpers/DefaultToolchain.swift
  TestApp/.swift-version
Labels: dependencies

#86 Propagate package manifest parsing errors
  Sources/SwiftToolchain/Toolchain.swift
Labels: bug

#88 Fix broken `carton init` templates
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Model/Template.swift
Labels: bug

#90 Update `README.md` to reflect the current feature set
  README.md
Labels: documentation

#93 Update dependencies
  Package.resolved
Labels: dependencies

#94 Update dependencies
  Package.resolved
Labels: dependencies

#95 Update dependencies
  Package.resolved
Labels: dependencies

#98 Update `tokamak` template for the new TokamakUI org
  Sources/carton/Model/Template.swift
Labels: refactor

#97 Implement `carton bundle` command
  .gitignore
  .vscode/tasks.json
  Package.swift
  README.md
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/carton-release/Formula.swift
  Sources/carton-release/HashArchive.swift
  Sources/carton/Carton.swift
  Sources/carton/Commands/Bundle.swift
  Sources/carton/Commands/SDK/Install.swift
  Sources/carton/Commands/SDK/Local.swift
  Sources/carton/Commands/SDK/SDK.swift
  Sources/carton/Commands/SDK/Versions.swift
  Sources/carton/Helpers/FileSystem.swift
  Sources/carton/Model/Dependency.swift
  Sources/carton/Server/Application.swift
  Sources/carton/Server/HTML.swift
  Sources/carton/Server/StaticArchive.swift
  bundle.config.js
  dev.config.js
  entrypoint/bundle.js
  package.json
Labels: enhancement

#101 Implement `--custom-index-page` option
  .swiftlint.yml
  .vscode/tasks.json
  Package.resolved
  Package.swift
  README.md
  Sources/carton/Commands/Bundle.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Helpers/ByteString.swift
  Sources/carton/Helpers/FileSystem.swift
  Sources/carton/Server/Application.swift
  Sources/carton/Server/HTML.swift
  Sources/carton/Server/Server.swift
  TestApp/index.html
Labels: enhancement
