Repository swiftwasm/carton, pull requests merged in 2020-07, with the labels that each got.

#27 Update WASI polyfill, print a backtrace on crash
  Sources/carton/Commands/Dev.swift
  Sources/carton/Commands/Versions.swift
  Sources/carton/Model/Dependency.swift
  Sources/carton/Toolchain/ToolchainManagement.swift
  TestApp/.swift-version
  TestApp/Sources/TestApp/main.swift
  entrypoint/dev.js
  package-lock.json
  package.json
Labels: dependencies, enhancement

#28 Log archive size when downloading new SDK
  Sources/carton/Toolchain/ToolchainManagement.swift
Labels: enhancement

#29 Sort the output of `carton sdk versions`
  Sources/carton/Toolchain/ToolchainManagement.swift
Labels: enhancement

#30 Fix backtrace logging for async startWasiTask
  Sources/carton/Commands/Dev.swift
  Sources/carton/Model/Dependency.swift
  entrypoint/dev.js
Labels: bug

#32 Update dependencies
  Package.resolved
Labels: dependencies

#33 Bump OpenCombine version to 0.10.0
  Package.swift
Labels: dependencies

#34 Use `from` instead of `upToNextMinor` for OpenCombine
  Package.swift
Labels: dependencies

#36 Update dependencies
  Package.resolved
Labels: dependencies

#41 Automatically link Foundation w/ destination.json
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  TestApp/Sources/TestApp/main.swift
Labels: enhancement

#43 Update dependencies
  Package.resolved
Labels: dependencies

#44 Avoid displaying destination files as SDK versions
  Sources/SwiftToolchain/ToolchainManagement.swift
Labels: bug

#46 Add sources to watcher per target
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Dev.swift
  TestApp/CustomPathTarget/text.swift
  TestApp/Package.swift
  TestApp/Sources/TestApp/main.swift
Labels: bug

#47 Update to Vapor 4.15.2, fix formatting
  Package.resolved
  Package.swift
  Package@swift-5.2.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Server/Server.swift
  TestApp/Sources/TestApp/main.swift
Labels: dependencies

#48 Fix watcher missing root directories
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Helpers/FileSystem.swift
Labels: bug

#50 Update dependencies
  Package.resolved
Labels: dependencies

#49 Always pass --enable-test-discovery to swift build
  Sources/SwiftToolchain/Toolchain.swift
  TestApp/Tests/LinuxMain.swift
Labels: enhancement

#51 Implement simple wasmer runner for `test` command
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton/Carton.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Commands/Test.swift
  TestApp/Tests/LinuxMain.swift
  TestApp/Tests/Tests/Test.swift
  TestApp/Tests/Tests/XCTestManifests.swift
Labels: enhancement

#52 Add `list` flag and `testCases` argument to `test`
  .vscode/tasks.json
  Package.resolved
  Sources/carton/Commands/Test.swift
Labels: enhancement

#40 Implement `carton sdk local` subcommand
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton/Commands/Local.swift
  Sources/carton/Commands/SDK.swift
  Sources/carton/Commands/Versions.swift
Labels: enhancement

#53 Fix `carton test` output skipping lines
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton/Commands/Local.swift
  Sources/carton/Commands/Test.swift
  Sources/carton/Commands/Versions.swift
Labels: bug

#55 Update dependencies
  Package.resolved
Labels: dependencies

#57 Update dependencies
  Package.resolved
Labels: dependencies

#59 Upgrade JavaScriptKit to 0.5.0
  package-lock.json
  package.json
Labels: dependencies

#58 Update dependencies
  Package.resolved
Labels: dependencies

#60 Update static.zip, automate its release process
  .gitignore
  Package.swift
  Package@swift-5.2.swift
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton-release/Formula.swift
  Sources/carton-release/HashArchive.swift
  Sources/carton-release/main.swift
  Sources/carton/Carton.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Commands/Init.swift
  Sources/carton/Commands/Install.swift
  Sources/carton/Commands/ListTemplates.swift
  Sources/carton/Commands/Local.swift
  Sources/carton/Commands/SDK.swift
  Sources/carton/Commands/Test.swift
  Sources/carton/Commands/Versions.swift
  Sources/carton/Model/Dependency.swift
  Sources/carton/Model/Template.swift
  Sources/carton/Server/StaticArchive.swift
  TestApp/Package.resolved
  TestApp/Package.swift
  entrypoint/favicon.ico
  package-lock.json
  webpack.config.js
Labels: dependencies

#62 Update dependencies
  Package.resolved
Labels: dependencies

#61 Propagate test build/run failures in the exit code
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/carton/Helpers/Expectation.swift
Labels: bug

#63 Update dependencies
  Package.resolved
Labels: dependencies

#64 Update dependencies
  Package.resolved
Labels: dependencies

#66 Warn against Xcode 12 betas in `README.md`
  README.md
Labels: bug, documentation

#68 Update dependencies
  Package.resolved
Labels: dependencies

#67 Fix watcher crashing in package subdirectories
  .vscode/tasks.json
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Combine/Watcher.swift
  Sources/carton/Helpers/FileSystem.swift
Labels: bug

#70 Update dependencies
  Package.resolved
Labels: dependencies

#69 Add verbose/concise logging levels
  Sources/CartonHelpers/TerminalController.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Server/Server.swift
Labels: enhancement

#75 Avoid using 3rd-party action for the Linux build
  .github/workflows/swift.yml
Labels: continuous integration

#74 Update TSC and add sqlite dependency
  Package.resolved
Labels: dependencies

#73 Fix crash caused by use of `try!` while installing invalid version
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
Labels: bug

#76 Update dependencies
  Package.resolved
Labels: dependencies

#79 Update dependencies
  Package.resolved
Labels: dependencies
