Repository swiftwasm/carton, pull requests merged in 2020-09, with the labels that each got.

#106 Bump default toolchain version, fix release builds
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/carton/Commands/Bundle.swift
Labels: bug, dependencies

#104 Implement support for static resources in `carton dev`
  README.md
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Server/Application.swift
  Sources/carton/Server/Server.swift
  TestApp/.swift-version
  TestApp/Package.resolved
  TestApp/Package.swift
  TestApp/Sources/TestApp/data.json
  TestApp/Sources/TestApp/main.swift
Labels: enhancement

#107 Bump JavaScriptKit dependency to 0.6.0
  Sources/CartonHelpers/FileSystem.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton-release/HashArchive.swift
  Sources/carton/Model/Dependency.swift
  Sources/carton/Server/StaticArchive.swift
  TestApp/.swift-version
  TestApp/Package.resolved
  TestApp/Package.swift
  TestApp/Sources/TestApp/main.swift
  package-lock.json
  package.json
Labels: dependencies

#108 Update node.js dependencies, including wasmer.js
  package-lock.json
  package.json
Labels: dependencies

#109 Implement resources copying in `carton bundle`
  Sources/CartonHelpers/TerminalController.swift
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Bundle.swift
  Sources/carton/Server/Application.swift
Labels: enhancement

#105 Update dependencies
  Package.resolved
Labels: dependencies

#111 Bump dependencies and default toolchain snapshot
  .github/workflows/swift.yml
  .swift-version
  Brewfile
  Package.resolved
  Package.swift
  Package@swift-5.2.swift
  Sources/CartonHelpers/DefaultToolchain.swift
  TestApp/.swift-version
  TestApp/Sources/TestApp/main.swift
Labels: dependencies

#115 Bump JavaScriptKit to 0.7.2
  Sources/carton/Server/StaticArchive.swift
  TestApp/Package.resolved
  TestApp/Package.swift
  TestApp/Sources/TestApp/main.swift
  package-lock.json
  package.json
Labels: dependencies

#113 Use raw stdout if TerminalController is unavailable
  .github/workflows/swift.yml
  .swiftformat
  .vscode/tasks.json
  Brewfile
  Package.swift
  Sources/CartonHelpers/HTTPClient.swift
  Sources/CartonHelpers/InteractiveWriter.swift
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/CartonHelpers/TerminalController.swift
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/ProgressAnimation.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton-release/HashArchive.swift
  Sources/carton/Commands/Bundle.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Commands/Init.swift
  Sources/carton/Commands/ListTemplates.swift
  Sources/carton/Commands/Package.swift
  Sources/carton/Commands/SDK/Install.swift
  Sources/carton/Commands/SDK/Local.swift
  Sources/carton/Commands/SDK/Versions.swift
  Sources/carton/Commands/Test.swift
  Sources/carton/Model/Dependency.swift
  Sources/carton/Model/Template.swift
  Sources/carton/Server/HTML.swift
  Sources/carton/Server/Server.swift
  install_ubuntu_deps.sh
  package.json
Labels: bug, continuous integration
