Repository swiftwasm/carton, pull requests merged in 2020-12, with the labels that each got.

#173 Bump JSKit, add support for testing in browsers
  .github/workflows/swift.yml
  .vscode/tasks.json
  Sources/SwiftToolchain/Builder.swift
  Sources/carton-release/HashArchive.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Commands/Test.swift
  Sources/carton/Model/Entrypoint.swift
  Sources/carton/Server/Application.swift
  Sources/carton/Server/Server.swift
  Sources/carton/Server/StaticArchive.swift
  TestApp/Tests/Tests/TrivialTest.swift
  entrypoint/bundle.config.js
  entrypoint/dev.config.js
  entrypoint/test.config.js
  entrypoint/test.js
  package-lock.json
  package.json
Labels: dependencies, enhancement

#171 Use `FileDownloadDelegate` from the AHC package
  Package.swift
  Sources/SwiftToolchain/FileDownloadDelegate.swift
  Sources/SwiftToolchain/ToolchainInstallation.swift
Labels: refactor

#176 Serve main bundle resources from root directory
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Commands/Bundle.swift
  Sources/carton/Commands/Dev.swift
  Sources/carton/Commands/Test.swift
  Sources/carton/Server/Application.swift
  Sources/carton/Server/Server.swift
  TestApp/Package.resolved
  TestApp/Package.swift
  TestApp/Sources/TestApp/main.swift
Labels: enhancement

#182 Bump versions of libraries in `Template.swift`
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton/Model/Template.swift
Labels: dependencies

#180 Mark all commands as implemented in `README.md`
  README.md
Labels: documentation

#184 Update dependencies
  Package.resolved
Labels: dependencies

#186 Add support for Chrome and Safari stack traces
  Sources/CartonHelpers/Parsers/ChromeStackTrace.swift
  Sources/CartonHelpers/Parsers/SafariStackTrace.swift
  Sources/CartonHelpers/StackTrace.swift
  Sources/SwiftToolchain/DestinationEnvironment.swift
  Sources/carton/Server/Server.swift
  Tests/CartonTests/StackTraceTests.swift
  entrypoint/dev.js
Labels: enhancement

#189 Fix parsing system targets in `Package.swift`
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/Toolchain.swift
  Tests/CartonTests/StackTraceTests.swift
Labels: bug

#188 Update dependencies
  Package.resolved
Labels: dependencies

#190 Update dependencies
  Package.resolved
Labels: dependencies

#191 Changes to project structure to allow for better testability
  Brewfile.lock.json
  Package.resolved
  Package.swift
  Package@swift-5.2.swift
  Sources/Carton/main.swift
  Sources/CartonCLI/Carton.swift
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Init.swift
  Sources/CartonCLI/Commands/ListTemplates.swift
  Sources/CartonCLI/Commands/Package.swift
  Sources/CartonCLI/Commands/SDK/Install.swift
  Sources/CartonCLI/Commands/SDK/Local.swift
  Sources/CartonCLI/Commands/SDK/SDK.swift
  Sources/CartonCLI/Commands/SDK/Versions.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/CartonKit/Combine/Watcher.swift
  Sources/CartonKit/Helpers/ByteString.swift
  Sources/CartonKit/Helpers/Expectation.swift
  Sources/CartonKit/Helpers/URL.swift
  Sources/CartonKit/Model/Entrypoint.swift
  Sources/CartonKit/Model/Project.swift
  Sources/CartonKit/Model/Template.swift
  Sources/CartonKit/Server/Application.swift
  Sources/CartonKit/Server/Environment+UserAgent.swift
  Sources/CartonKit/Server/HTML.swift
  Sources/CartonKit/Server/Server.swift
  Sources/CartonKit/Server/StaticArchive.swift
  Tests/CartonCLITests/CommandTestHelper.swift
  Tests/CartonCLITests/DevCommandTests.swift
  Tests/CartonCLITests/StringHelpers.swift
  Tests/CartonTests/CartonTests.swift
Labels: refactor

#192 Add Dev tests and fix hard coded paths
  .github/workflows/swift.yml
  Dockerfile
  Package.resolved
  Package.swift
  Package@swift-5.2.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton-release/HashArchive.swift
  Tests/CartonCLITests/DevCommandTests.swift
  Tests/CartonCommandTests/CommandTestHelper.swift
  Tests/CartonCommandTests/DevCommandTests.swift
  Tests/CartonCommandTests/InitCommandTests.swift
  Tests/CartonCommandTests/StringHelpers.swift
  Tests/CartonCommandTests/Testable.swift
Labels: good first issue, refactor

#196 Add tests for `dev` and `bundle` commands
  .github/workflows/swift.yml
  Package.swift
  Package@swift-5.2.swift
  Tests/CartonCommandTests/BundleCommandTests.swift
  Tests/CartonCommandTests/CommandTestHelper.swift
  Tests/CartonCommandTests/DevCommandTests.swift
  Tests/CartonCommandTests/StringHelpers.swift
  Tests/Fixtures/Milk/.gitignore
  Tests/Fixtures/Milk/Package.resolved
  Tests/Fixtures/Milk/Package.swift
  Tests/Fixtures/Milk/README.md
  Tests/Fixtures/Milk/Sources/Milk/main.swift
  Tests/Fixtures/Milk/Tests/LinuxMain.swift
  Tests/Fixtures/Milk/Tests/MilkTests/MilkTests.swift
  Tests/Fixtures/Milk/Tests/MilkTests/XCTestManifests.swift
  package-lock.json
Labels: continuous integration

#198 Add `test` command test with no arguments
  .dockerignore
  .github/workflows/swift.yml
  .gitignore
  Dockerfile
  Tests/CartonCommandTests/TestCommandTests.swift
  Tests/Fixtures/carton-test/TestApp/CustomPathTarget/text.swift
  Tests/Fixtures/carton-test/TestApp/Package.resolved
  Tests/Fixtures/carton-test/TestApp/Package.swift
  Tests/Fixtures/carton-test/TestApp/Sources/TestApp/data.json
  Tests/Fixtures/carton-test/TestApp/Sources/TestApp/main.swift
  Tests/Fixtures/carton-test/TestApp/Sources/TestLibrary/text.swift
  Tests/Fixtures/carton-test/TestApp/Tests/Tests/TrivialTest.swift
  Tests/Fixtures/carton-test/TestApp/index.html
Labels: continuous integration, refactor
