Repository swiftwasm/carton, pull requests merged in 2021-05, with the labels that each got.

#240 Avoid building in `release` mode when testing
  .github/workflows/swift.yml
  Tests/LinuxMain.swift
Labels: continuous integration

#239 Fix `carton dev` crashing with SO sanitizer
  .github/workflows/swift.yml
  .vscode/tasks.json
  Package.swift
  Package@swift-5.2.swift
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/CartonKit/Model/Entrypoint.swift
  Sources/CartonKit/Server/Application.swift
  Sources/CartonKit/Server/Server.swift
  Sources/CartonKit/Server/StaticArchive.swift
  Sources/SwiftToolchain/BuildDescription.swift
  Sources/SwiftToolchain/Builder.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton-release/HashArchive.swift
  Tests/CartonCommandTests/CommandTestHelper.swift
  Tests/Fixtures/TestApp/Package.resolved
  Tests/Fixtures/TestApp/Package.swift
  Tests/Fixtures/TestApp/Sources/TestApp/main.swift
Labels: bug, refactor

#232 Update dependencies
  Package.resolved
Labels: dependencies

#228 Add more browsers to `DestinationEnvironment`
  Sources/CartonKit/Server/Environment+UserAgent.swift
Labels: bug

#242 Fix Ubuntu deps, clarify Linux support in README
  README.md
  install_ubuntu_deps.sh
Labels: dependencies, documentation

#243 Update JSKit and Tokamak versions in templates
  Sources/CartonKit/Model/Template.swift
  Sources/SwiftToolchain/Toolchain.swift
Labels: dependencies

#245 Update dependencies
  Package.resolved
Labels: dependencies

#244 Bump version to 0.10.0, update `CHANGELOG.md`
  CHANGELOG.md
  Sources/CartonHelpers/Version.swift
  Tests/CartonTests/CartonTests.swift
  package-lock.json
  package.json
Labels: documentation
