Repository swiftwasm/carton, pull requests merged in 2021-11, with the labels that each got.

#263 Update dependencies, add support for SwiftWasm 5.5
  .github/workflows/swift.yml
  Package.resolved
  Package.swift
  Package@swift-5.2.swift
  README.md
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/SwiftToolchain/Manifest.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Tests/CartonCommandTests/CommandTestHelper.swift
  Tests/CartonCommandTests/DevCommandTests.swift
  Tests/CartonCommandTests/TestCommandTests.swift
Labels: dependencies, continuous integration

#265 Update JavaScriptKit to v0.11.1
  Sources/CartonKit/Model/Entrypoint.swift
  Sources/CartonKit/Server/StaticArchive.swift
  Sources/SwiftToolchain/Toolchain.swift
  package-lock.json
  package.json
Labels: dependencies

#266 Use SwiftWasm 5.5.0, bump version to 0.12.0
  Package.resolved
  Package.swift
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/CartonHelpers/Version.swift
  Sources/SwiftToolchain/ToolchainInstallation.swift
  Tests/Fixtures/TestApp/Package.resolved
  Tests/Fixtures/TestApp/Package.swift
  package-lock.json
  package.json
Labels: dependencies

#267 Update `CHANGELOG.md` for 0.12.0, bump Tokamak
  CHANGELOG.md
  Sources/CartonKit/Model/Template.swift
  Tests/Fixtures/Milk/Package.swift
Labels: documentation, dependencies

#261 Update dependencies
  Package.resolved
Labels: dependencies
