Repository swiftwasm/carton, pull requests merged in 2021-01, with the labels that each got.

#202 Fix browser testing for Safari, update tasks.json
  .swiftlint.yml
  .vscode/tasks.json
  Sources/CartonCLI/Commands/Test.swift
  Sources/SwiftToolchain/Toolchain.swift
  Tests/CartonCommandTests/TestCommandTests.swift
  Tests/Fixtures/TestApp/CustomPathTarget/text.swift
  Tests/Fixtures/TestApp/Package.resolved
  Tests/Fixtures/TestApp/Package.swift
  Tests/Fixtures/TestApp/Sources/TestApp/data.json
  Tests/Fixtures/TestApp/Sources/TestApp/main.swift
  Tests/Fixtures/TestApp/Sources/TestLibrary/text.swift
  Tests/Fixtures/TestApp/Tests/Tests/TrivialTest.swift
  Tests/Fixtures/TestApp/index.html
Labels: bug

#204 Avoid running tests while building the Docker image
  Dockerfile
Labels: continuous integration

#207 Update the "Roadmap" section in `README.md`
  README.md
Labels: documentation

#210 Link to the org sponsorship page from `README.md`
  README.md
Labels: documentation

#209 ci/carton test --environment defaultbrowser
  Tests/CartonCommandTests/CommandTestHelper.swift
  Tests/CartonCommandTests/DevCommandTests.swift
  Tests/CartonCommandTests/TestCommandTests.swift
Labels: continuous integration

#211 Update dependencies
  Package.resolved
Labels: dependencies

#213 Add host argument to `dev` and `test` commands
  .github/workflows/swift.yml
  Brewfile.lock.json
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/CartonKit/Server/Application.swift
  Sources/CartonKit/Server/Server.swift
  Tests/CartonCommandTests/DevCommandTests.swift
Labels: enhancement

#214 Update dependencies
  Package.resolved
Labels: dependencies

#194 Use libSwiftPM instead of custom model types
  Package.resolved
  Package.swift
  Package@swift-5.2.swift
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/CartonHelpers/Parsers/ChromeStackTrace.swift
  Sources/CartonHelpers/Parsers/DiagnosticsParser.swift
  Sources/CartonHelpers/Parsers/FirefoxStackTrace.swift
  Sources/CartonHelpers/Parsers/SafariStackTrace.swift
  Sources/CartonHelpers/Parsers/String+Regex.swift
  Sources/CartonHelpers/Parsers/TestsParser.swift
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/CartonKit/Model/Entrypoint.swift
  Sources/CartonKit/Server/Application.swift
  Sources/CartonKit/Server/Server.swift
  Sources/SwiftToolchain/Builder.swift
  Sources/SwiftToolchain/Manifest.swift
  Sources/SwiftToolchain/Package.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainInstallation.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton-release/Formula.swift
Labels: refactor

#217 Add test for `carton sdk install`
  Package.resolved
  Sources/CartonHelpers/Parsers/ChromeStackTrace.swift
  Sources/CartonHelpers/Parsers/DiagnosticsParser.swift
  Sources/CartonHelpers/Parsers/FirefoxStackTrace.swift
  Sources/CartonHelpers/Parsers/SafariStackTrace.swift
  Sources/CartonHelpers/Parsers/String+Regex.swift
  Sources/CartonHelpers/Parsers/TestsParser.swift
  Sources/SwiftToolchain/Manifest.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainInstallation.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Tests/CartonCommandTests/SDKCommandTests.swift
Labels: continuous integration
