Repository swiftwasm/carton, pull requests merged in 2022-09, with the labels that each got.

#379 Ignore force_try swift-lint rule where in defer.
  Sources/CartonCLI/Commands/TestRunners/BrowserTestRunner.swift
Labels: bug

#378 Use @main attributes
  Sources/CartonKit/Model/Template.swift
  Tests/CartonCommandTests/InitCommandTests.swift
Labels: bug

#380 Add 5.7 host toolchain matrix
  .github/workflows/swift.yml
  Package.resolved
  Package.swift
Labels: enhancement

#381 Update SwiftPM library version to 5.7
  Package.resolved
  Package.swift
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/SwiftToolchain/Manifest.swift
  Sources/SwiftToolchain/Toolchain.swift
  Tests/CartonCommandTests/CommandTestHelper.swift
  Tests/CartonTests/CartonTests.swift
Labels: dependencies

#383 Update default toolchain version to 5.7.1
  Dockerfile
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/CartonKit/Model/Template.swift
  Tests/CartonCommandTests/InitCommandTests.swift
Labels: enhancement
