Repository swiftwasm/carton, pull requests merged in 2022-03, with the labels that each got.

#300 Add -Xswiftc option for each build commands
  Dockerfile
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Options.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/SwiftToolchain/BuildFlavor.swift
  Sources/SwiftToolchain/Toolchain.swift
  Tests/CartonCommandTests/BundleCommandTests.swift
Labels: enhancement

#302 Use libSwiftPM 5.6 to parse manifests
  Package.resolved
  Package.swift
  Sources/CartonHelpers/Parsers/DiagnosticsParser.swift
  Sources/CartonKit/Server/Server.swift
  Sources/SwiftToolchain/Manifest.swift
  Sources/SwiftToolchain/Toolchain.swift
Labels: bug, dependencies

#301 Add --debug-info flag to carton bundle
  Brewfile
  Sources/CartonCLI/Commands/Bundle.swift
  Tests/CartonCommandTests/BundleCommandTests.swift
  Tests/CartonCommandTests/CommandTestHelper.swift
  install_ubuntu_deps.sh
Labels: enhancement

#303 Add macOS 12 and Xcode 13.3 to CI matrix
  .github/workflows/swift.yml
  Tests/CartonCommandTests/CommandTestHelper.swift
  Tests/CartonCommandTests/DevCommandTests.swift
Labels: continuous integration

#298 Update dependencies
  Package.resolved
Labels: dependencies

#304 Don't strip custom sections when --debug-info
  Sources/CartonCLI/Commands/Bundle.swift
Labels: bug
