Repository swiftwasm/carton, pull requests merged in 2022-05, with the labels that each got.

#324 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies

#325 Fix 5.6 template: use `executableTarget`
  Sources/CartonKit/Model/Template.swift
Labels: refactor

#329 Update to v2 of Contributor Covenant in shared GitHub repo
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#330 Serve all available resources with `dev`/`bundle`
  .swiftlint.yml
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/CartonHelpers/FileSystem.swift
  Sources/CartonKit/Server/Application.swift
  Sources/CartonKit/Server/Server.swift
Labels: bug

#332 Add `carton`/SwiftWasm/JSKit compat matrix to `README.md`
  README.md
Labels: documentation

#333 Clarify `--environment` option for `carton test` in `README.md`
  README.md
Labels: documentation

#334 Embed static.zip in Swift code instead of downloading from remote
  Sources/CartonKit/Model/Entrypoint.swift
  Sources/CartonKit/Server/StaticArchive.swift
  Sources/carton-release/HashArchive.swift
Labels: refactor

#338 Fix JavaScriptBigIntSupport compatibility issue
  Package.resolved
  Package.swift
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/SwiftToolchain/BuildFlavor.swift
  Sources/SwiftToolchain/Builder.swift
  Sources/SwiftToolchain/DestinationEnvironment.swift
  Sources/SwiftToolchain/Toolchain.swift
Labels: bug

#335 Use JSKit runtime from SwiftPM resources
  .github/workflows/swift.yml
  .swiftformat
  Package.resolved
  Package.swift
  Sources/CartonCLI/Commands/TestRunners/NodeTestRunner.swift
  Sources/CartonHelpers/Process.swift
  Sources/CartonKit/Server/Application.swift
  Sources/CartonKit/Server/HTML.swift
  Sources/CartonKit/Server/Server.swift
  Sources/CartonKit/Server/StaticArchive.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/carton-release/HashArchive.swift
  Tests/CartonCommandTests/DevCommandTests.swift
  Tests/CartonCommandTests/TestCommandTests.swift
  Tests/Fixtures/Milk/Package.resolved
  Tests/Fixtures/Milk/Package.swift
  Tests/Fixtures/NodeJSKitTest/.gitignore
  Tests/Fixtures/NodeJSKitTest/Package.resolved
  Tests/Fixtures/NodeJSKitTest/Package.swift
  Tests/Fixtures/NodeJSKitTest/Sources/NodeJSKitTest/main.swift
  Tests/Fixtures/NodeJSKitTest/Tests/NodeJSKitTestTests/NodeJSKitTestTests.swift
  Tests/Fixtures/TestApp/Package.resolved
  Tests/Fixtures/TestApp/Package.swift
  entrypoint/bundle.config.js
  entrypoint/bundle.js
  entrypoint/common.js
  entrypoint/dev.config.js
  entrypoint/dev.js
  entrypoint/test.config.js
  entrypoint/test.js
  entrypoint/testNode.config.js
  entrypoint/testNode.js
  package-lock.json
  package.json
Labels: enhancement

#342 Re-read custom `index.html` on updates
  .github/workflows/swift.yml
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/TestRunners/BrowserTestRunner.swift
  Sources/CartonKit/Server/Application.swift
  Sources/CartonKit/Server/HTML.swift
  Sources/CartonKit/Server/Server.swift
Labels: bug

#347 Fix watcher breakage on failed builds
  Sources/CartonKit/Server/Server.swift
  Tests/Fixtures/NodeJSKitTest/.gitignore
Labels: bug

#348 Bump version to 0.15.0, update `CHANGELOG.md`
  CHANGELOG.md
  README.md
  Sources/CartonHelpers/Version.swift
  Tests/Fixtures/Milk/Package.resolved
  Tests/Fixtures/Milk/Package.swift
  package-lock.json
  package.json
Labels: documentation

#349 Fix symlinks not fully cleaned up in Node.js tests
  Sources/CartonHelpers/FileSystem.swift
Labels: bug

#350 Add missing check for Node.js entrypoint
  Sources/CartonCLI/Commands/TestRunners/NodeTestRunner.swift
Labels: bug

#351 Use standards mode in default index page
  Sources/CartonKit/Server/HTML.swift
  Tests/CartonCommandTests/DevCommandTests.swift
Labels: enhancement

#353 Stop limiting WS frame size to 16kb for large number of test suites
  Sources/CartonKit/Server/Application.swift
Labels: bug

#355 Clean up integration tests and fixtures
  Package.swift
  Tests/CartonCommandTests/BundleCommandTests.swift
  Tests/CartonCommandTests/DevCommandTests.swift
  Tests/CartonCommandTests/InitCommandTests.swift
  Tests/CartonCommandTests/IntegrationTests.swift
  Tests/CartonCommandTests/SDKCommandTests.swift
  Tests/CartonCommandTests/TestCommandTests.swift
  Tests/CartonCommandTests/Testable.swift
  Tests/Fixtures/EchoExecutable/Package.swift
  Tests/Fixtures/EchoExecutable/Sources/my-echo/main.swift
  Tests/Fixtures/Milk/.gitignore
  Tests/Fixtures/Milk/Package.resolved
  Tests/Fixtures/Milk/Package.swift
  Tests/Fixtures/Milk/README.md
  Tests/Fixtures/Milk/Sources/Milk/main.swift
  Tests/Fixtures/Milk/Tests/LinuxMain.swift
  Tests/Fixtures/Milk/Tests/MilkTests/MilkTests.swift
  Tests/Fixtures/Milk/Tests/MilkTests/XCTestManifests.swift
Labels: refactor

#356 Fix linter error in `Builder.swift`
  Sources/SwiftToolchain/Builder.swift
Labels: refactor

#357 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies
