Repository swiftwasm/carton, pull requests merged in 2022-06, with the labels that each got.

#359 Add option to disable wasm optimizations
  README.md
  Sources/CartonCLI/Commands/Bundle.swift
  Tests/CartonCommandTests/BundleCommandTests.swift
Labels: enhancement

#360 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies

#362 Headless test runner
  Package.swift
  README.md
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/CartonCLI/Commands/TestRunners/BrowserTestRunner.swift
  Sources/CartonKit/Server/Server.swift
  Sources/WebDriverClient/WebDriverClient.swift
  Tests/CartonCommandTests/TestCommandTests.swift
  Tests/WebDriverClientTests/WebDriverClientTests.swift
Labels: enhancement

#363 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies

#365 Revert "Use `--static-swift-stdlib` for easier distribution on Linux"
  .github/workflows/swift.yml
  Dockerfile
  install_ubuntu_deps.sh
Labels: bug

#366 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies

#368 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies
