Repository swiftwasm/carton, pull requests merged in 2022-04, with the labels that each got.

#306 Bump JavaScriptKit dependency to 0.13.0
  Sources/CartonKit/Model/Entrypoint.swift
  Sources/CartonKit/Server/StaticArchive.swift
  Sources/SwiftToolchain/Toolchain.swift
  package-lock.json
  package.json
Labels: dependencies

#305 Bump version to 0.13.0, update `CHANGELOG.md`
  CHANGELOG.md
  Sources/CartonHelpers/Version.swift
  package-lock.json
  package.json
Labels: documentation

#307 Fix watcher blocked by Vapor `run()`
  Sources/CartonKit/Server/Server.swift
Labels: bug

#308 Describe `--debug-info` and `-Xswiftc` in `README.md`
  README.md
Labels: documentation

#309 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies

#310 Several fixes for 5.6 toolchain
  Package.resolved
  Package.swift
  Sources/CartonHelpers/DefaultToolchain.swift
  Sources/CartonKit/Model/Entrypoint.swift
  Sources/CartonKit/Model/Template.swift
  Sources/CartonKit/Server/StaticArchive.swift
  Sources/SwiftToolchain/Toolchain.swift
  Tests/CartonCommandTests/DevCommandTests.swift
  Tests/CartonCommandTests/TestCommandTests.swift
  Tests/Fixtures/Milk/Package.resolved
  Tests/Fixtures/Milk/Package.swift
  Tests/Fixtures/TestApp/Package.resolved
  Tests/Fixtures/TestApp/Package.swift
  entrypoint/bundle.js
  entrypoint/dev.js
  entrypoint/test.js
  package.json
Labels: bug, dependencies

#311 Bump version to 0.14.0, update `CHANGELOG.md`
  .gitignore
  CHANGELOG.md
  Sources/CartonHelpers/Version.swift
  package-lock.json
  package.json
Labels: documentation

#312 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies

#314 Fix "No export `_start` found in the module" error in `carton test`
  Sources/SwiftToolchain/Toolchain.swift
  Tests/CartonCommandTests/TestCommandTests.swift
Labels: bug

#316 Bump version to 0.14.1 and update `CHANGELOG.md`
  CHANGELOG.md
  Sources/CartonHelpers/Version.swift
  package-lock.json
  package.json
Labels: documentation

#319 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies

#320 Update SwiftPM dependencies
  Package.resolved
Labels: dependencies

#323 Override clock_res_get function from wasmer/wasi-js to fix memory issue
  entrypoint/bundle.js
  entrypoint/dev.js
  entrypoint/test.js
Labels: bug
