Repository swiftwasm/carton, pull requests merged in 2022-01, with the labels that each got.

#272 Build `main` Docker images on every push to `main` branch
  .github/workflows/docker.yml
Labels: continuous integration

#275 Statically link with `SwiftPMDataModel` library
  Dockerfile
  Package.resolved
  Package.swift
Labels: dependencies

#284 Update dependencies
  Package.resolved
Labels: dependencies

#283 Use `async`/`await` and actors instead of Combine
  .github/workflows/swift.yml
  Package.resolved
  Package.swift
  README.md
  Sources/Carton/Main.swift
  Sources/Carton/main.swift
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Init.swift
  Sources/CartonCLI/Commands/Package.swift
  Sources/CartonCLI/Commands/SDK/Install.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/CartonHelpers/Async.swift
  Sources/CartonHelpers/AsyncFileDownload.swift
  Sources/CartonHelpers/Process.swift
  Sources/CartonHelpers/ProcessRunner.swift
  Sources/CartonKit/Model/Template.swift
  Sources/CartonKit/Server/Application.swift
  Sources/CartonKit/Server/Server.swift
  Sources/SwiftToolchain/Builder.swift
  Sources/SwiftToolchain/ProgressAnimation.swift
  Sources/SwiftToolchain/Toolchain.swift
  Sources/SwiftToolchain/ToolchainInstallation.swift
  Sources/SwiftToolchain/ToolchainManagement.swift
  Sources/carton-release/HashArchive.swift
  Sources/carton-release/Main.swift
  Tests/Fixtures/Milk/Package.resolved
Labels: refactor

#286 Upgrade binaryen version to 105
  install_ubuntu_deps.sh
Labels: dependencies

#288 Add libsqlite3-dev dependency
  install_ubuntu_deps.sh
Labels: bug, dependencies

#289 Update dependencies
  Package.resolved
Labels: dependencies
