Repository swiftwasm/carton, pull requests merged in 2024-04, with the labels that each got.

#427 Stop using the setup-swift action
  .github/workflows/swift.yml
Labels: continuous integration

#426 Fix test harness for the latest main XCTest
  Sources/CartonKit/Server/StaticArchive.swift
  entrypoint/common.js
  package-lock.json
  package.json
Labels: bug

#428 entrypointをTypeScriptにする
  Sources/CartonKit/Server/StaticArchive.swift
  Sources/carton-release/HashArchive.swift
  entrypoint/JavaScriptKit_JavaScriptKit.resources/Runtime/index.d.ts
  entrypoint/bundle.ts
  entrypoint/common.ts
  entrypoint/dev.ts
  entrypoint/test.ts
  entrypoint/testNode.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#431 Stop writing static files in ~/.carton/static
  Plugins/CartonTest/Plugin.swift
  Sources/CartonCLI/Commands/Bundle.swift
  Sources/CartonCLI/Commands/Dev.swift
  Sources/CartonCLI/Commands/Test.swift
  Sources/CartonCLI/Commands/TestRunners/BrowserTestRunner.swift
  Sources/CartonCLI/Commands/TestRunners/NodeTestRunner.swift
  Sources/CartonKit/Model/Entrypoint.swift
  Sources/CartonKit/Server/StaticArchive.swift
  Sources/carton-release/HashArchive.swift
Labels: refactor
